# Generated by Django 5.0.3 on 2024-03-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0002_cidade_estado_profissao_ousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ousuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='ousuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ousuario',
            name='exerce',
        ),
        migrations.RemoveField(
            model_name='ousuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Profissao',
        ),
        migrations.DeleteModel(
            name='ousuario',
        ),
    ]
