# Generated by Django 5.0.3 on 2024-04-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0003_remove_ousuario_cidade_remove_ousuario_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indicadores',
        ),
    ]
